---
title: "Citas Tesis"
format:
  pdf:
    toc: true
    toc-title: "Indice de Contenidos"
    number-sections: true
    colorlinks: true
    fontfamily: libertinus
bibliography: citas.bib
csl: apa.csl
link-citations: yes
linkcolor: blue
---
\pagebreak

## DESCRIPCIÓN

### Capitulo 1

"...En aquel Imperio, el Arte de la Cartografía logró tal Perfección que el mapa de una sola Provincia ocupaba toda una Ciudad y el mapa del imperio, toda una Provincia. Con el tiempo, esos Mapas Desmesurados no satisfacieron y los Colegios de Cartógrafos levantaron un Mapa del Imperio, que tenía el tamaño del Imperio y coincidía puntualmente con él. Menos Adictas al Estudio de la Cartografía, las Generaciones Siguientes entendieron que ese dilatado Mapa era Inútil y no sin Impiedad lo entregaron a las Inclemencias del Sol y de los Inviernos. En los desiertos del Oeste perduran despedazadas Ruinas del Mapa, habitadas por Animales y por Mendigos; en todo el País no hay otra reliquia de las Disciplinas Geográficas."

[@Borges1965]



"Lo conocido es finito, lo desconocido infinito; desde el punto de vista intelectual estamos en una pequeña isla enmedio deun océano de ilimitable de inexplicabilidad. Nuestra tarea en cada generación es recuperar algo más de tierra".

(Huxley, T. 1887)


"Preferiría comprender una sola causa que ser Rey de Persia."

Demócrito de Abdera

"Y al cabo, nada os debo; debéisme cuanto he escrito. 


"A mi trabajo acudo, con mi dinero pago 

el traje que me cubre y la mansión que habito, 

el pan que me alimenta y el lecho en donde yago.

Y cuando llegue el día del último vïaje, 

y esté al partir la nave que nunca ha de tornar, 

me encontraréis a bordo ligero de equipaje, 

casi desnudo, como los hijos de la mar."

(Antonio Machado, 1938)

"En el amor, locura es lo sensato"

Antonio Machado, 1938)

...algo de *"talento pero me falta añquiñar un escritorio"*

Borges a Ortega y Gasset


"Pido permiso, señores
Que este tango
Este tango habla por mí
Y mi voz entre sus sones dirá
Dirá por qué canto así
Porque cuando pibe
Porque cuando pibe me acunaba en tangos
La canción materna pa' llamar el sueño
Y escuché el rezongo de los bandoneones
Bajo el emparrado de mi patio viejo
Porque vi el desfile de las inclemencias
Con mis pobres ojos llorosos y abiertos
Y en la triste pieza de mis buenos viejos
Cantó la pobreza su canción de invierno
Y yo me hice en tangos
Me fui modelando en barro, en miseria
En las amarguras que da la pobreza
En llantos de madre
En la rebeldía del que es fuerte y tiene que cruzar los brazos
Cuando el hambre viene
Y yo me hice en tangos porque
Porque el tango es macho
Porque el tango es fuerte
Tiene olor a vida
Tiene gusto a muerte
Porque quise mucho
Y porque me engañaron
Y pasé la vida masticando sueños
Porque soy un árbol que nunca dio frutos
Porque soy un perro que no tiene dueño
Porque tengo odios que nunca los digo
Porque cuando quiero, ja
Porque cuando quiero me desangro en besos
Porque quise mucho y no me han querido
Por eso canto tan triste, ¡por eso!"

(La Cumparsita. Julio Soza)


\pagebreak

## REFERENCIAS